name: Bug Report
description: Report something that is not working (as it should)
title: "[BUG] "
labels: [BUG]
body:
  - type: input
    id: version
    attributes:
      label: FaStQL version
      description: Select which version of FaStQL you are using
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A short but clear description of the issue
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: Steps to reproduce
      description: A detailed list of steps to reproduce the bug
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Node.js version, related network settings, etc
    validations:
      required: true